package com.example.vehiclemaintenancerebuild.dataclass

open class VehicleManufacturerListConstants {

    object ManufacturerList {
        val manufacturerListObject = listOf<String>(
            "Alfa Romeo",
            "Ariel",
            "Aprilia",
            "Aston Martin",
            "Audi",
            "BAC",
            "Benelli",
            "Bentley",
            "BMW",
            "Bowler",
            "British Leyland",
            "Bugatti",
            "Buick",
            "Cadillac",
            "Caterham",
            "CF Moto",
            "Chevrolet",
            "Chrysler",
            "Citroen",
            "Dacia",
            "Dodge",
            "DS",
            "Ducati",
            "Ferrari",
            "Fiat",
            "Ford",
            "Ginetta",
            "GMC",
            "Harley Davidson",
            "Honda",
            "Hummer",
            "Husqvarna",
            "Hyundai",
            "Indian",
            "Infiniti",
            "Jaguar",
            "Jeep",
            "Kawasaki",
            "Keeway",
            "Kia",
            "KTM",
            "Koenigsegg",
            "Lamborghini",
            "Land Rover",
            "Lexmoto",
            "Lexus",
            "Lotus",
            "Maserati",
            "Mazda",
            "McLaren",
            "Mercedes-Benz",
            "MG",
            "Mini",
            "Mitsubishi",
            "Morgan",
            "Morris",
            "Moto Guzzi",
            "MV Augusta",
            "Nissan",
            "Noble",
            "OPEL",
            "Pagani",
            "Peugeot",
            "Piaggio",
            "Porsche",
            "Renault",
            "Rolls-Royce",
            "Royal Enfield",
            "Saab",
            "SEAT",
            "Sinnis",
            "Škoda",
            "Suzuki",
            "SYM",
            "Tesla",
            "Toyota",
            "Triumph",
            "TVR",
            "Vauxhall",
            "Volkswagen",
            "Volvo",
            "Yamaha",
            "Yamasaki",
            "Zontes"
        )

    }
}